#!/usr/bin/env python3
"""
Generate labeled training data for the Layer 1 intent classifier.
Output: data/training_intents.jsonl
Each line: {"text": "...", "label": "file_task"}
"""

import json
from pathlib import Path

EXAMPLES = {
    "file_task": [
        # Search/query
        "find all PDFs in my Downloads folder",
        "show me all Python files in my home directory",
        "list files I modified today",
        "find images larger than 5MB",
        "show me all files modified in the last week",
        "find all text files in Documents",
        "list all zip files anywhere in my home",
        "show me my largest files",
        "find all markdown files",
        "list files that start with report",
        "find all mp3 and mp4 files",
        "show me files modified before 2023",
        "find all log files in my home directory",
        "list all files in my Desktop folder",
        "find Excel spreadsheets modified this year",
        "find files named exactly budget.xlsx",
        "list all hidden files in my home directory",
        "find files between 1MB and 10MB",
        "show me folders in my Documents directory",
        "find my tax stuff",
        "where are my photos",
        "show me stuff I downloaded recently",
        "find files I created this month",
        "list all CSV files",
        "find duplicate file names",
        "show me recently modified documents",
        "find all files with no extension",
        "list files in my projects folder",
        "find all backup files",
        "show me the newest files in Downloads",
        # Move/copy/organize
        "move all PDFs from Desktop to Documents",
        "copy my photos to the backup folder",
        "rename all files in Downloads to lowercase",
        "move old files to archive folder",
        "organize my Downloads by file type",
        "copy the project files to backup",
        "move all logs older than a month to archive",
        "rename budget2023 to budget2024",
        "move my tax documents to the taxes folder",
        "copy important files to external drive",
        # Delete
        "delete all .tmp files in home",
        "remove all duplicate photos",
        "clean up old log files from last year",
        "delete empty folders in Downloads",
        "remove all .pyc cache files",
        # Read content
        "show me the contents of my README file",
        "open and display my notes.txt",
        "read the config file in my project",
        "show me what is in that text file",
        "display the log file from yesterday",
        # Natural phrasing
        "I need to find all my invoices",
        "where did I put that PDF",
        "help me organize my downloads",
        "show me what is in my documents folder",
        "I want to see all my photos",
        "clean up my desktop files",
        "find everything from last year",
        "what files did I work on today",
        "I am looking for a spreadsheet",
        "where are my project files",
        "find the file I was working on yesterday",
        "list all scripts in my home directory",
        "show me files ending in .conf",
        "find all files newer than last week",
        "what is in my downloads",
        "show me all word documents",
        "find any file named todo",
        "list all directories in my home folder",
        "find all files I created this year",
        "show me the biggest files I have",
        "find old videos in my home directory",
        "list all JSON files in the project",
        "show me all config files",
        "find all test files in the codebase",
        "where did I save that document",
        "show me all files from last month",
    ],
    "email_task": [
        "find emails from last week",
        "show me unread emails",
        "search my inbox for invoices",
        "find emails from john@example.com",
        "show me emails with attachments",
        "find emails about the project meeting",
        "list emails I sent yesterday",
        "find all emails from my boss",
        "show me emails older than 30 days",
        "search for emails mentioning budget",
        "find emails with PDF attachments",
        "show me starred emails",
        "find the email thread about the contract",
        "list all emails from newsletters",
        "find emails I need to reply to",
        "show me emails from last month",
        "find emails mentioning deadline",
        "search for emails about the conference",
        "list emails with large attachments",
        "find emails I flagged as important",
        "show me all sent emails this week",
        "find the email with the flight confirmation",
        "search inbox for receipts",
        "find emails from the team",
        "show me emails about the proposal",
        "compose an email to my manager",
        "write an email thanking the client",
        "draft a reply to the job offer",
        "send a follow-up email to sales team",
        "write a professional email declining the meeting",
    ],
    "web_task": [
        "search the web for Python tutorials",
        "look up the weather in Tokyo",
        "find information about machine learning",
        "search for best restaurants near me",
        "look up how to install Arch Linux",
        "find the latest news about AI",
        "search for Python documentation",
        "look up the price of a MacBook",
        "find tutorials on Rust programming",
        "search for open source projects",
        "look up the current Bitcoin price",
        "find reviews for the new iPhone",
        "search for recipes with chicken",
        "look up how to fix this error",
        "find the documentation for React",
        "search for jobs as a software engineer",
        "look up the population of Kazakhstan",
        "find articles about climate change",
        "search for the best VPN services",
        "look up flight prices to London",
        "find a YouTube video about Linux",
        "search for apartments in Almaty",
        "look up the meaning of this word",
        "find the API documentation",
        "search for open source alternatives to Photoshop",
        "browse to the GitHub page",
        "fetch the contents of that URL",
        "look up the exchange rate",
        "find the Wikipedia article about this",
        "search online for this topic",
        "go to that website",
        "open the browser and find this",
        "check the news online",
        "google how to do this",
        "look this up on the internet",
        "find an online tutorial",
        "check what the internet says about this",
        "search for that on the web",
        "visit the official website",
        "look up the online manual",
        "find it online",
        "check online if this is available",
        "what does Google say about this",
        "find a Stack Overflow answer",
        "look for this on Reddit",
    ],
    "system_task": [
        "show me system information",
        "check my CPU usage",
        "show me how much RAM I am using",
        "list all running processes",
        "check disk space",
        "show network connections",
        "what processes are using the most memory",
        "check my battery status",
        "show me system logs",
        "list all installed packages",
        "check if a port is open",
        "show me the current date and time",
        "what is my IP address",
        "list all background services",
        "check if a service is running",
        "show me environment variables",
        "what user am I logged in as",
        "check kernel version",
        "list all mounted drives",
        "show me the process tree",
        "how long has the system been running",
        "check CPU temperature",
        "show active network interfaces",
        "list all open files",
        "check system performance",
        "kill the process using port 8080",
        "restart the nginx service",
        "show me memory usage over time",
        "list all cron jobs",
        "what version of Python is installed",
    ],
    "writing_task": [
        "write a summary of my project",
        "draft an email to my team",
        "create a README for this project",
        "write a cover letter",
        "summarize this document",
        "translate this text to Spanish",
        "write a meeting agenda",
        "create a todo list",
        "draft a report on this topic",
        "write a short bio",
        "create documentation for this code",
        "write a blog post about AI",
        "draft a proposal for the client",
        "summarize the key points",
        "write a thank you email",
        "create a project plan",
        "draft a job description",
        "write release notes",
        "create a FAQ document",
        "summarize this article",
        "write a LinkedIn post",
        "draft a response to this message",
        "create a presentation outline",
        "write a technical specification",
        "draft a contract clause",
        "proofread this paragraph",
        "rewrite this sentence more formally",
        "generate ideas for the presentation",
        "write a commit message for these changes",
        "create a changelog entry",
        "help me write this document",
        "compose a formal letter",
        "draft a press release",
        "write a product description",
        "create an executive summary",
        "write a weekly status update",
        "draft an announcement for the team",
        "write a review of this code",
        "compose a resignation letter",
        "create a meeting summary from these notes",
    ],
}

OUTPUT_PATH = Path("data/training_intents.jsonl")
OUTPUT_PATH.parent.mkdir(exist_ok=True)

lines = []
for label, texts in EXAMPLES.items():
    for text in texts:
        lines.append(json.dumps({"text": text, "label": label}))

OUTPUT_PATH.write_text("\n".join(lines) + "\n")

counts = {label: len(texts) for label, texts in EXAMPLES.items()}
total = sum(counts.values())
print(f"Generated {total} training examples:")
for label, count in sorted(counts.items()):
    print(f"  {label}: {count}")
print(f"Saved to: {OUTPUT_PATH}")
