[preferred]
default=leaves;gtk
org.freedesktop.impl.portal.Screenshot=leaves
org.freedesktop.impl.portal.ScreenCast=leaves
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.AppChooser=gtk
