[preferred]
default=marshal;gtk
org.freedesktop.impl.portal.Screenshot=marshal
org.freedesktop.impl.portal.ScreenCast=marshal
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.AppChooser=gtk
